services:
  - type: web
    name: budget-mobile-app
    runtime: node
    buildCommand: cd budget-mobile-app && npm install && npm run build
    startCommand: cd budget-mobile-app && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 