services:
  - type: web
    name: budget-mobile-app
    runtime: node
    buildCommand: cd budget-mobile-app && npm install --include=dev && npm run build
    startCommand: cd budget-mobile-app && node server/api.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_MONGODB_URI
        sync: false
      - key: VITE_MONGODB_DB
        sync: false
      - key: VITE_API_URL
        value: https://budget-mobile-app-pa2n.onrender.com
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://budget-mobile-app-pa2n.onrender.com
    healthCheckPath: /health
    autoDeploy: true 