services:
  - type: web
    name: budget-mobile-app
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_MONGODB_URI
        sync: false
      - key: VITE_MONGODB_DB
        sync: false
      - key: VITE_API_URL
        value: https://budget-mobile-app.onrender.com
    healthCheckPath: /
    autoDeploy: true 